name: Documentation

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Setup python environment
        run: |
          sudo apt install pipx
          pipx ensurepath
          pipx install poetry
          poetry install
      - name: Build docs
        run: poetry run mkdocs build
      - name: Publish docs
        run: poetry run mkdocs gh-deploy --force
