name: Build and publish python package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Setup python environment
        run: |
          sudo apt install pipx
          pipx ensurepath
          pipx install poetry

      - name: Install package
        run: poetry install --without dev

      - name: Build package
        run: poetry build

      - name: Publish package
        run: |
          poetry config pypi-token.pypi "${{ secrets.PYPI_API_KEY }}"
          poetry publish
