name: Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
            python-version: 3.12
      - name: Setup python environment
        run: |
          sudo apt install pipx
          pipx ensurepath
          pipx install poetry
          poetry install
      - name: Setup env config
        run: |
          cp .env.example .env
      - name: Setup docker compose
        run: sudo apt install docker-compose
      - name: Start services
        run: docker-compose up -d
      - name: Wait for services to be healthy
        run: |
          while ! docker-compose exec -T postgis pg_isready -U admin -d db; do
            sleep 1
          done
          while ! docker-compose exec -T geoserver curl -f http://localhost:8080; do
            sleep 1
          done
      - name: Test
        run: poetry run python -m pytest tests/
