name: Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Setup env config
        run: |
          cp .env.example .env
          sed -i 's/GEOSERVER_HOST=localhost/GEOSERVER_HOST=127.0.0.1/' .env
          sed -i 's/POSTGRES_HOST=localhost/POSTGRES_HOST=127.0.0.1/' .env

      - name: Setup docker services
        run: sudo apt install docker-compose

      - name: Start services
        run: docker-compose up -d

      - name: Setup python environment
        run: |
          sudo apt install pipx
          pipx ensurepath
          pipx install poetry
          poetry install

      - name: Run tests
        run: poetry run python -m pytest tests/
